import { clsx, type ClassValue } from "clsx";
import { extendTailwindMerge } from "tailwind-merge";

const twMerge = extendTailwindMerge({
  extend: {
    classGroups: {
      "font-size": [
        {
          text: [
            "h1",
            "h2",
            "h3",
            "h4",
            "h5",
            "h6",
            "h7",
            "h8",
            "h9",
            "s1",
            "s2",
            "s3",
            "s4",
            "s5",
            "s6",
            "s7",
            "s8",
            "s9",
            "b1",
            "b2",
            "b3",
            "b4",
            "b5",
            "b6",
            "b7",
            "b8",
            "b9",
          ],
        },
      ],
      "text-color": [
        {
          text: [
            "primary-10",
            "primary-20",
            "primary-30",
            "primary-40",
            "primary-50",
            "primary-60",
            "primary-70",
            "primary-80",
            "primary-90",
            "secondary-10",
            "secondary-20",
            "secondary-30",
            "secondary-40",
            "secondary-50",
            "secondary-60",
            "secondary-70",
            "secondary-80",
            "secondary-90",
            "tertiary-10",
            "tertiary-20",
            "tertiary-30",
            "tertiary-40",
            "tertiary-50",
            "tertiary-60",
            "tertiary-70",
            "tertiary-80",
            "tertiary-90",
            "neutral-10",
            "neutral-100",
            "neutral-200",
            "neutral-300",
            "neutral-400",
            "neutral-500",
            "neutral-600",
            "neutral-700",
            "neutral-800",
            "neutral-900",
            "neutral-1000",
            "red-10",
            "red-100",
            "red-200",
            "yellow-10",
            "yellow-100",
            "yellow-200",
            "green-10",
            "green-100",
            "green-200",
          ],
        },
      ],
    },
  },
});

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
